---
- name: Manage DevOps users
  hosts: webservers
  become: true

  tasks:
    - name: Create DevOps user
      ansible.builtin.user:
        name: "{{ devops_user }}"
        shell: /bin/bash
        create_home: true
        groups: sudo
        append: true
        state: present

    - name: Create SSH directory for DevOps user
      ansible.builtin.file:
        path: "/home/{{ devops_user }}/.ssh"
        state: directory
        owner: "{{ devops_user }}"
        group: "{{ devops_user }}"
        mode: "0700"